"""backlog коннектим к регистрациям, а не к бойцам

Revision ID: b1b0b31f39f5
Revises: 
Create Date: 2022-06-09 06:55:57.972694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b0b31f39f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backlogDB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_backlogDB_fighter_id_participantsDB', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_backlogDB_reg_id_registrationsDB'), 'registrationsDB', ['reg_id'], ['reg_id'])
        batch_op.drop_column('fighter_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backlogDB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fighter_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_backlogDB_reg_id_registrationsDB'), type_='foreignkey')
        batch_op.create_foreign_key('fk_backlogDB_fighter_id_participantsDB', 'participantsDB', ['fighter_id'], ['participant_id'])
        batch_op.drop_column('reg_id')

    # ### end Alembic commands ###
